### ISSUE TITLE
Crash on worldload 1.4.7 & 1.4.8.31 [MC 1.9.4]

### ISSUE THREAD

**Issue by Cirrus0** [legendblade/CraftingHarmonics#111] opened 2016-06-16 16:12 UTC
When i tried to update from version 1.4.6.29 i get a repeatable crash on world load.

```
java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.getSkyColorBody(World.java:1470)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:403)
	at org.winterblade.minecraft.harmony.world.ProxiedWorldProvider.getSkyColor(ProxiedWorldProvider.java:373)
```

Since i didn't know which updated mod caused it and tried multiple times to make sure i also have multiple crash logs for you. 

Happens with versions 1.4.7 and 1.4.8.31, does **not** happen with 1.4.6.29.

**1.4.7:**
[crash-2016-06-16_17.46.47-client.txt](https://github.com/legendblade/CraftingHarmonics/files/318849/crash-2016-06-16_17.46.47-client.txt)

**1.4.8.31:**
[crash-2016-06-16_17.53.03-client.txt](https://github.com/legendblade/CraftingHarmonics/files/318850/crash-2016-06-16_17.53.03-client.txt)
[crash-2016-06-16_17.37.41-client.txt](https://github.com/legendblade/CraftingHarmonics/files/318851/crash-2016-06-16_17.37.41-client.txt)
[crash-2016-06-16_17.40.10-client.txt](https://github.com/legendblade/CraftingHarmonics/files/318852/crash-2016-06-16_17.40.10-client.txt)

**Comment by legendblade** [comment] 2016-06-16 20:31
Hi.  Sorry, I've been out all day.  I'll try and get a fix for this as soon as possible... just as soon as I figure out what's causing the problem.

Thanks.

**Comment by Cirrus0** [comment] 2016-06-16 20:42
No problem, i am probably several hours ahead of you anyway ;)
I suspect it could have something to do with the combination between biomes'o plenty and your mod?

**Comment by legendblade** [comment] 2016-06-16 20:48
That is possible, though, preliminary tests with new instances just aren't yielding any results so far.  I'd originally suspected it might be a coremod interfering, but, that's looking less likely now.

Couple of quick questions: 
- Does this only happen with existing worlds, or new worlds as well?
- Do you have anything configured with Crafting Harmonics, especially sky color modifications?  If you do, could I get a copy of your configs for it?

Thanks.

**Comment by Cirrus0** [comment] 2016-06-16 20:56
I just dropped you a message on curseforge (i hope ;) )

It happens directly after creating a new world, just before you actually join

**Comment by legendblade** [comment] 2016-06-16 20:58
Wow, that's definitely going above and beyond; I've been spending the past 10 minutes or so going through the mod list in Curse and manually getting each one so I can track it down, so, that helps a lot.

Thanks. :)

**Comment by Cirrus0** [comment] 2016-06-16 21:11
Hm, i just was kind of confused because i could not reproduce the crash with the list i just sent you and the newest version. So i thought about what i changed and i removed one mod because it would not start on the server.

Try adding [Super Crafting Frame](http://minecraft.curseforge.com/projects/super-crafting-frame?gameCategorySlug=mc-mods&projectID=73926) to the list i gave you. I am pretty unsure how this affects the skycolor-getter of your mod, but it seems those two are currently not compatible?

**Comment by legendblade** [comment] 2016-06-16 21:19
I just tried it both with and without Super Crafting Frame, and I'm unable to reproduce it in either version.  I did end up having to remove Inventory Tweaks due to an unrelated crash, so, maybe there's something else happening.

That said, I did just notice you said you were running it on a server, so, I'll take a bit to confirm that I'm not seeing similar issues on a server instance instead of just a client instance.

**Comment by Cirrus0** [comment] 2016-06-16 21:21
The problem has so far not happened on the server, just in the singleplayer.

**Comment by legendblade** [comment] 2016-06-16 22:06
Alright.  So, I think I tracked down the cause of the problem - which I'm fairly confident in saying isn't something that Crafting Harmonics is doing wrong, but it's just showing up as something from CH because I'm wrapping the call to that particular method.

I'll put in some added safeguards for things, which should prevent the world from crashing, but, I'm not 100% certain it'll fix things since I'm still not sure the actual root cause of the crash.

**Closed** 2016-06-16 22:24 UTC
Labels: bug

**Comment by legendblade** [comment] 2016-06-16 22:26
Alright, it's currently building and getting uploaded to CurseForge; should be available in the next 10-15 minutes.  That said...

Best case scenario: this will stop the crashes from occurring.
Worst case scenario: it makes your sky color permanently solid black.

If it's the second, please let me know, and we'll run through some more troubleshooting steps to try and pinpoint the issue a bit better.

Thanks.
