### ISSUE TITLE
[Bug] addAlchemyArray "binding" is missing

### ISSUE THREAD

**Issue by JAWSAWN** [legendblade/CraftingHarmonics#106] opened 2016-06-07 15:35 UTC

**Comment by legendblade** [comment] 2016-06-07 23:36
Is this a duplicate of #107?

Thanks.

**Comment by JAWSAWN** [comment] 2016-06-07 23:51
whops messed up

**Comment by legendblade** [comment] 2016-06-07 23:51
No problem.  Just wanted to confirm.  Thanks.

**Closed** 2016-06-07 23:51 UTC
